services:
  - type: web
    name: tarflow-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: PLUGGY_CLIENT_ID
        sync: false
      - key: PLUGGY_CLIENT_SECRET
        sync: false
